In [39]:
#1. Импорт библиотеки NumPy

import numpy as np 
arr = np.array([1, 2, 3]) # создание массива arr
arr

array([1, 2, 3])

In [7]:
arr.shape # форма массива

(3,)

In [40]:
#2. Примеры создания массивов

arr_zer = np.zeros((3,4)) # массив из нулей
arr_ones = np.ones(5)     # массив из нулей
arr_arange = np.arange(5,100,10) # массив с заданным диапазоном

arr_zer,arr_ones,arr_arange

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([1., 1., 1., 1., 1.]),
 array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95]))

In [42]:
#3. Демонстрация атрибутов shape и dtype

arr_zer.shape, arr_zer.dtype  # форма и тип данных массива

((3, 4), dtype('float64'))

In [27]:
#4. Примеры индексирования и срезов:

arr_arange[4] # получение отдельного элемента

np.int64(45)

In [29]:
arr_arange[1:8:2] # срез

array([15, 35, 55, 75])

In [32]:
#5. Векторные операции и статистика
ADR1 = np.array([52,42,37,86,34,91,120])
ADR2 = np.array([32,49,26,10,109,74,65])
summa = ADR1 + ADR2
multiplication = ADR1 * ADR2
summa, multiplication

(array([ 84,  91,  63,  96, 143, 165, 185]),
 array([1664, 2058,  962,  860, 3706, 6734, 7800]))

In [35]:
ADR1.mean() # среднее значение

np.float64(66.0)

In [38]:
min_ADR1 = min(ADR1) # минимальное значение
max_ADR2 = max(ADR2) # максимальное значение
min_ADR1, max_ADR2

(np.int64(34), np.int64(109))